### ISSUE TITLE
Address sanitizer fails tests - iceccd read beyond end of buffer

### ISSUE THREAD

**Issue by HenryMiller1** [icecc/icecream#213]
When memory sanitizer is run on iceccd it fails with the error:

```
=================================================================
==8426== ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60040000ddb2 at pc 0x44b7d2 bp 0x7ffe42d6c680 sp 0x7ffe42d6c678
READ of size 1 at 0x60040000ddb2 thread T0
    #0 0x44b7d1 in std::char_traits<char>::length(char const*) /usr/include/c++/4.8/bits/char_traits.h:259
    #1 0x44b7d1 in std::string::assign(char const*) /usr/include/c++/4.8/bits/basic_string.h:1131
    #2 0x44b7d1 in std::string::operator=(char const*) /usr/include/c++/4.8/bits/basic_string.h:555
    #3 0x44b7d1 in MsgChannel::MsgChannel(int, sockaddr*, unsigned int, bool) /home/user/icecream/services/comm.cpp:766
    #4 0x44e5f3 in Service::createChannel(int, sockaddr*, unsigned int) /home/user/icecream/services/comm.cpp:746
    #5 0x417023 in Daemon::answer_client_requests() /home/user/icecream/daemon/main.cpp:1824
    #6 0x418369 in Daemon::working_loop() /home/user/icecream/daemon/main.cpp:1964
    #7 0x41ac79 in main /home/user/icecream/daemon/main.cpp:2294
    #8 0x2afbe3f0cf44 (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)
    #9 0x4057a8 in _start (/home/user/icecream/daemon/iceccd+0x4057a8)
0x60040000ddb2 is located 0 bytes to the right of 2-byte region [0x60040000ddb0,0x60040000ddb2)
allocated by thread T0 here:
    #0 0x2afbe012741a (/usr/lib/x86_64-linux-gnu/libasan.so.0+0x1541a)
    #1 0x44b659 in MsgChannel::MsgChannel(int, sockaddr*, unsigned int, bool) /home/user/icecream/services/comm.cpp:762
    #2 0x44e5f3 in Service::createChannel(int, sockaddr*, unsigned int) /home/user/icecream/services/comm.cpp:746
    #3 0x417023 in Daemon::answer_client_requests() /home/user/icecream/daemon/main.cpp:1824
    #4 0x418369 in Daemon::working_loop() /home/user/icecream/daemon/main.cpp:1964
    #5 0x41ac79 in main /home/user/icecream/daemon/main.cpp:2294
    #6 0x2afbe3f0cf44 (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)
SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/include/c++/4.8/bits/char_traits.h:259 std::char_traits<char>::length(char const*)
Shadow bytes around the buggy address:
  0x0c00ffff9b60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c00ffff9b70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c00ffff9b80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c00ffff9b90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c00ffff9ba0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c00ffff9bb0: fa fa fa fa fa fa[02]fa fa fa 00 07 fa fa 00 00
  0x0c00ffff9bc0: fa fa fd fd fa fa fd fd fa fa 00 00 fa fa 00 00
  0x0c00ffff9bd0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c00ffff9be0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c00ffff9bf0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c00ffff9c00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:     fa
  Heap righ redzone:     fb
  Freed Heap region:     fd
  Stack left redzone:    f1
  Stack mid redzone:     f2
  Stack right redzone:   f3
  Stack partial redzone: f4
  Stack after return:    f5
  Stack use after scope: f8
  Global redzone:        f9
  Global init order:     f6
  Poisoned by user:      f7
  ASan internal:         fe
==8426== ABORTING
```

The failing memory allocation in comm.cpp is ```addr = (struct sockaddr *)malloc(addr_len);``` If change it to
    addr = (struct sockaddr *)malloc(addr_len + 2);
this test passes.  This of course is not the right fix.

**Comment by HenryMiller1** [comment]
tests are passing now.
