### ISSUE TITLE
Assertion of iceccd on SIGINT

### ISSUE THREAD

**Issue by danny-smit** [icecc/icecream#280]
When a compilation is started using icecc and killed prematurely using ctrl+c on the running compilation, the iceccd aborts with an assertion.

```
[7430] 11:09:08: create_env_finished gcc
[7430] 11:09:08: native_environment /var/cache/icecream/native/cf1644d73a4fde82685a1d51dbdbd30c.tar.gz
[7430] 11:09:08: cache_size = 17597382
[7430] 11:09:08: handle_get_cs 1
[7430] 11:09:08: handle_get_cs 2
[7430] 11:09:08: handle_get_cs 3
[7430] 11:09:08: handle_get_cs 4
[7430] 11:09:08: handle_use_cs 149 1 0x555555784ee0 192.168.178.91 192.168.178.91
[7430] 11:09:08: handle_use_cs 150 2 0x555555785300 192.168.178.220 192.168.178.91
[7430] 11:09:08: handle_use_cs 151 3 0x555555785690 192.168.178.220 192.168.178.91
[7430] 11:09:08: pending pending_use_cs local unix domain socket: (B eof: 0) CID: 1 ID: 149 CS: 127.0.0.1
[7430] 11:09:08: handle_use_cs 152 4 0x555555785a20 192.168.178.220 192.168.178.91
[7430] 11:09:08: send JobLocalBeginMsg to client
[7430] 11:09:08: pushed local job 3
[7430] 11:09:08: scheduler->send_msg( JobDoneMsg( clientwork local unix domain socket: (B eof: 0) CID: 3 ID: 151 CS: 192.168.178.220, 119))
[7430] 11:09:08: send JobLocalBeginMsg to client
[7430] 11:09:08: pushed local job 2
[7430] 11:09:08: accepted 14 local unix domain socket
[7430] 11:09:08: get_native_env /var/cache/icecream/native/cf1644d73a4fde82685a1d51dbdbd30c.tar.gz (gcc)
[7430] 11:09:08: handle_get_cs 5
[7430] 11:09:08: handle_use_cs 155 5 0x555555785690 192.168.178.220 192.168.178.91
[7430] 11:09:08: scheduler->send_msg( JobDoneMsg( clientwork local unix domain socket: (B eof: 0) CID: 2 ID: 150 CS: 192.168.178.220, 119))
[7430] 11:09:08: send JobLocalBeginMsg to client
[7430] 11:09:08: pushed local job 4
[7430] 11:09:08: accepted 15 local unix domain socket
[7430] 11:09:08: get_native_env /var/cache/icecream/native/cf1644d73a4fde82685a1d51dbdbd30c.tar.gz (gcc)
[7430] 11:09:08: handle_get_cs 6
[7430] 11:09:08: handle_use_cs 157 6 0x555555785300 192.168.178.220 192.168.178.91
[7430] 11:09:08: scheduler->send_msg( JobDoneMsg( clientwork local unix domain socket: (B eof: 0) CID: 4 ID: 152 CS: 192.168.178.220, 119))
[7430] 11:09:08: send JobLocalBeginMsg to client
[7430] 11:09:08: pushed local job 5
[7430] 11:09:08: saw eof without complete msg! 1
iceccd: main.cpp:1503: void Daemon::handle_end(Client*, int): Assertion `false' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff69e71d7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7.x86_64 libcap-ng-0.7.5-4.el7.x86_64 libgcc-4.8.5-11.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 lzo-2.06-8.el7.x86_64
(gdb) where
#0  0x00007ffff69e71d7 in raise () from /lib64/libc.so.6
#1  0x00007ffff69e88c8 in abort () from /lib64/libc.so.6
#2  0x00007ffff69e0146 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff69e01f2 in __assert_fail () from /lib64/libc.so.6
#4  0x0000555555560f82 in Daemon::handle_end (this=this@entry=0x7fffffffd800, client=client@entry=0x555555785300, exitcode=exitcode@entry=118) at main.cpp:1503
#5  0x0000555555563220 in Daemon::handle_activity (this=this@entry=0x7fffffffd800, client=client@entry=0x555555785300) at main.cpp:1649
#6  0x0000555555563fa3 in Daemon::answer_client_requests (this=this@entry=0x7fffffffd800) at main.cpp:1935
#7  0x000055555556434d in Daemon::working_loop (this=this@entry=0x7fffffffd800) at main.cpp:2027
#8  0x000055555555b754 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:2356
```

It especially seems to occur for jobs that are built locally.

It seems similar to what was reported here https://github.com/icecc/icecream/issues/275 as a remark at the end of the report.

Tested with code of commit 22fcc39.

Please let me know what I can do to help troubleshoot the issue.

**Comment by HenryMiller1** [comment]
Can you run the daemon -vvvv when this happens and post the logs?

I'm suspecting this came in with #262, but I can't quite figure out the chain where this might fail.  It could be something else though.

**Comment by danny-smit** [comment]
Here is the full output with "-vvvv" as argument:
```
Starting program: /usr/sbin/iceccd -u icecc -b /var/cache/icecream -vvvv -m 2
[16992] 13:22:35: ICECREAM daemon 1.1rc3 starting up (nice level 5) 
[16992] 13:22:35: 2 CPU(s) online on this server
[16992] 13:22:35: allowing up to 2 active jobs
[16992] 13:22:35: not detaching
[16992] 13:22:35: already a process group leader
[16992] 13:22:35: ignoring localhost lo
[16992] 13:22:35: broadcast enp0s3 192.168.178.255
[16992] 13:22:35: Netnames:
[16992] 13:22:35: ICECREAM
[16992] 13:22:35: ignoring localhost lo
[16992] 13:22:35: broadcast enp0s3 192.168.178.255
[16992] 13:22:35: scheduler not yet found.
[16992] 13:22:35: Suitable scheduler found at 192.168.178.220:8765 (version: 35)
[16992] 13:22:35: scheduler not yet found.
[16992] 13:22:38: scheduler is on 192.168.178.220:8765 (net ICECREAM)
[16992] 13:22:38: Connected to scheduler (I am known as 192.168.178.91)
[16992] 13:22:49: accepted 13 local unix domain socket
[16992] 13:22:49: get_native_env  (gcc)
[16992] 13:22:49: start_create_env gcc
Detaching after fork from child process 17012.
[16992] 13:22:49: accepted 15 local unix domain socket
[16992] 13:22:49: get_native_env  (gcc)
[16992] 13:22:49: waiting for already running create_env gcc
[16992] 13:22:49: accepted 16 local unix domain socket
[16992] 13:22:49: get_native_env  (gcc)
[16992] 13:22:49: waiting for already running create_env gcc
[16992] 13:22:49: accepted 17 local unix domain socket
[16992] 13:22:49: get_native_env  (gcc)
[16992] 13:22:49: waiting for already running create_env gcc
cp: omitting directory ‘/lib’
cp: omitting directory ‘/lib64’
[16992] 13:22:52: create_env_finished gcc
[16992] 13:22:52: native_environment /var/cache/icecream/native/cf1644d73a4fde82685a1d51dbdbd30c.tar.gz
[16992] 13:22:52: cache_size = 17597387
[16992] 13:22:52: handle_get_cs 1
[16992] 13:22:52: handle_get_cs 2
[16992] 13:22:52: handle_get_cs 3
[16992] 13:22:52: handle_use_cs 63 1 0x555555784ee0 192.168.178.91 192.168.178.91
[16992] 13:22:52: handle_get_cs 4
[16992] 13:22:52: pending pending_use_cs local unix domain socket: (B eof: 0) CID: 1 ID: 63 CS: 127.0.0.1
[16992] 13:22:52: handle_use_cs 64 2 0x555555785300 192.168.178.220 192.168.178.91
[16992] 13:22:52: handle_use_cs 65 3 0x555555785690 192.168.178.220 192.168.178.91
[16992] 13:22:52: handle_use_cs 66 4 0x555555785a20 192.168.178.220 192.168.178.91
[16992] 13:22:52: send JobLocalBeginMsg to client
[16992] 13:22:52: pushed local job 2
[16992] 13:22:53: scheduler->send_msg( JobDoneMsg( clientwork local unix domain socket: (B eof: 0) CID: 2 ID: 64 CS: 192.168.178.220, 119))
[16992] 13:22:53: send JobLocalBeginMsg to client
[16992] 13:22:53: pushed local job 3
[16992] 13:22:53: accepted 14 local unix domain socket
[16992] 13:22:53: get_native_env /var/cache/icecream/native/cf1644d73a4fde82685a1d51dbdbd30c.tar.gz (gcc)
[16992] 13:22:53: handle_get_cs 5
[16992] 13:22:53: handle_use_cs 69 5 0x555555785300 192.168.178.220 192.168.178.91
[16992] 13:22:53: saw eof without complete msg! 1
iceccd: main.cpp:1503: void Daemon::handle_end(Client*, int): Assertion `false' failed.

Program received signal SIGABRT, Aborted.
```

(I'm not sure where the "cp omitting directory /lib64" error comes from yet, but that is probably unrelated)

**Comment by danny-smit** [comment]
I'm not sure if it helps, but I just added some more logging at the point of the assertion:

```
$ git diff
diff --git a/daemon/main.cpp b/daemon/main.cpp
index b18d3bf..4af0df0 100644
--- a/daemon/main.cpp
+++ b/daemon/main.cpp
@@ -1500,6 +1500,13 @@ void Daemon::handle_end(Client *client, int exitcode)
             case Client::LINKJOB:
             case Client::TOINSTALL:
             case Client::WAITCREATEENV:
+                log_error() << "client " << client->client_id << " should not have a job_id" << "\n\t" 
+                            << "job_id: " << job_id << "\n\t"
+                            << "client status: " << client->status << endl;
+                trace() << "client dump: " << client->dump() << ", exitcode: " << exitcode << "\n";
+                flush_debug();
+                log_error() << dump_internals() << endl;
+                flush_debug();
                 assert(false);   // should not have a job_id
                 break;
             case Client::WAITCOMPILE:
```

Which gives:
```
[21611] 14:46:43: create_env_finished gcc
[21611] 14:46:43: native_environment /var/cache/icecream/native/cf1644d73a4fde82685a1d51dbdbd30c.tar.gz
[21611] 14:46:43: cache_size = 17597379
[21611] 14:46:43: handle_get_cs 2
[21611] 14:46:43: handle_get_cs 3
[21611] 14:46:43: handle_get_cs 4
[21611] 14:46:43: handle_use_cs 120 2 0x7feb308221a0 192.168.178.91 192.168.178.91
[21611] 14:46:43: handle_get_cs 1
[21611] 14:46:43: pending pending_use_cs local unix domain socket: (B eof: 0) CID: 2 ID: 120 CS: 127.0.0.1
[21611] 14:46:43: handle_use_cs 121 3 0x7feb30822600 192.168.178.220 192.168.178.91
[21611] 14:46:43: handle_use_cs 122 4 0x7feb308229d0 192.168.178.220 192.168.178.91
[21611] 14:46:43: send JobLocalBeginMsg to client
[21611] 14:46:43: pushed local job 4
[21611] 14:46:43: handle_use_cs 123 1 0x7feb30821ee0 192.168.178.220 192.168.178.91
[21611] 14:46:44: scheduler->send_msg( JobDoneMsg( clientwork local unix domain socket: (B eof: 0) CID: 4 ID: 122 CS: 192.168.178.220, 119))
[21611] 14:46:44: send JobLocalBeginMsg to client
[21611] 14:46:44: pushed local job 1
[21611] 14:46:44: accepted 11 local unix domain socket
[21611] 14:46:44: get_native_env /var/cache/icecream/native/cf1644d73a4fde82685a1d51dbdbd30c.tar.gz (gcc)
[21611] 14:46:44: handle_get_cs 5
[21611] 14:46:44: handle_use_cs 126 5 0x7feb308229d0 192.168.178.220 192.168.178.91
[21611] 14:46:44: scheduler->send_msg( JobDoneMsg( clientwork local unix domain socket: (B eof: 0) CID: 1 ID: 123 CS: 192.168.178.220, 119))
[21611] 14:46:44: send JobLocalBeginMsg to client
[21611] 14:46:44: pushed local job 3
[21611] 14:46:44: accepted 9 local unix domain socket
[21611] 14:46:44: get_native_env /var/cache/icecream/native/cf1644d73a4fde82685a1d51dbdbd30c.tar.gz (gcc)
[21611] 14:46:44: handle_get_cs 6
[21611] 14:46:44: handle_use_cs 128 6 0x7feb30821ee0 192.168.178.220 192.168.178.91
[21611] 14:46:44: handle_job_done 120 0
[21611] 14:46:44: send JobLocalBeginMsg to client
[21611] 14:46:44: pushed local job 5
[21611] 14:46:44: accepted 10 local unix domain socket
[21611] 14:46:44: get_native_env /var/cache/icecream/native/cf1644d73a4fde82685a1d51dbdbd30c.tar.gz (gcc)
[21611] 14:46:44: handle_get_cs 7
[21611] 14:46:44: handle_use_cs 130 7 0x7feb308221a0 192.168.178.91 192.168.178.91
[21611] 14:46:44: saw eof without complete msg! 1
[21611] 14:46:44: client 6 should not have a job_id
        job_id: 128
        client status: 4
[21611] 14:46:44: client dump: linkjob local unix domain socket: (B eof: 1) CID: 6 /home/danny/icecream/services/tempfile.c, exitcode: 118
[21611] 14:46:44: Node Name: danny-test.localdomain
  Remote name: 192.168.178.91
  fd2chan[10] = local unix domain socket: (B eof: 0)
  fd2chan[11] = local unix domain socket: (B eof: 0)
  fd2chan[12] = local unix domain socket: (B eof: 0)
  client 7: pending_use_cs local unix domain socket: (B eof: 0) CID: 7 ID: 130 CS: 127.0.0.1
  client 3: clientwork local unix domain socket: (B eof: 0) CID: 3 ID: 121 CS: 192.168.178.220
  client 5: clientwork local unix domain socket: (B eof: 0) CID: 5 ID: 126 CS: 192.168.178.220
  Cache Size: 17597379
  Architecture: x86_64
  NativeEnv (gcc): /var/cache/icecream/native/cf1644d73a4fde82685a1d51dbdbd30c.tar.gz
  Now: 1501526804
  envs_last_use[/var/cache/icecream/native/cf1644d73a4fde82685a1d51dbdbd30c.tar.gz] = 1501526804
  Current kids: 0 (max: 2)
  Scheduler protocol: 35
  cpu: 491 idle, 0 nice
  load: 0.4, icecream_load: 116
  memory: 0 (free: 1139)

iceccd: main.cpp:1510: void Daemon::handle_end(Client*, int): Assertion `false' failed.
```

**Comment by danny-smit** [comment]
Another interesting thing, for testing purposes I reverted this commit: https://github.com/icecc/icecream/commit/1c15f6b9c6ddd329e4fe1e2a03c7420a0407ae25 (because I was having issues with icemon as described at https://github.com/icecc/icemon/issues/33) and after that I'm not able to reproduce this crash/assertion anymore. 

So there may be a relation to https://github.com/icecc/icecream/issues/282?

**Comment by trulyliu** [comment]
I met the same issue. When I use ctrl+c to interrupt compiling, 
iceccd always give this assert.

**Comment by trulyliu** [comment]
Thanks dany-smit, I revert 1c15f6b also。iceccd does not assert anymore.

There is another bug of 1c15f6b. Before I revert 1c15f6b,  In icecc-monitor, I can see the number of jobs on localhost keeps growing during compiling although the job capacity of localhost is 4.  it reach to more than thousands.   After revert 1c15f6b, jobs on localhost does not exceeds the capacity.

**Comment by HenryMiller1** [comment]
1c15f6b9c6ddd329e4fe1e2a03c7420a0407ae25 reverted
